// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvcjqxstkcecbazgrnmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2Y2pxeHN0a2NlY2Jhemdybm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTg5NDYsImV4cCI6MjA2OTY5NDk0Nn0.zuLJWqhnuUMCB6A36uvjBsUlaqt3xE1hvp9FDDrxxVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});